### ISSUE TITLE
DSM 3617xs. Failed to install the file. The file is probably corrupted.

### ISSUE THREAD

**Issue by GuS-eu** [pocopico/tinycore-redpill#12]
![image](https://user-images.githubusercontent.com/91498295/150789734-66c6c48a-4f41-4f1d-920a-5fac936549dd.png)

Successfully installed on DSM3615xs baremetal, but cannot install it on 3617xs.
I was following [this](https://xpenology.club/install-dsm-7-on-baremetal-or-vm/) guide, but I typed "sudo ./rploader.sh build broadwell-7.0.1-42218" in WINSCP PuTTY instead of "sudo ./rploader.sh build bromolow-7.0.1-42218" because its on 3617xs .So after going through all steps of this guide, at the last step where you need to select a .pat file the installing stopes at 56%.

I have no idea what could've cause this issue any help would be appreciated!

**Comment by gorskivarna** [comment]
same here.no luck with 3617xs. 3615xs working well

**Comment by phenixtai** [comment]
same the 3617xs don't work

**Comment by dipol0** [comment]
ho ho. i get PAT file after build tynycore dsm7.1 and have same problem, but... i download official Synology DSM7.1 img PAT file and try it - all install fine! (DS3615xs on VM)

**Comment by aniston** [comment]
Hi, same problem for a DS3615xs , I'm getting the same error at 56% with having built for DS3615xs using  `./rploader.sh build bromolow-7.0.1-42218` using the downloaded `DSM_DS3615xs_42218.pat` from the Synology website.

any suggestion where to look for errors or how to continue.

**Comment by dipol0** [comment]
@aniston you try install PAT file get from redpill build environment before flashing official synology PAT ? If YES - try full clear/erase all you disks (quickly - make new GPT/MBR partition)

**!!! PS. if you have important data - have backup !!!**

**Comment by aniston** [comment]
@dipol0 tried both ways, but alwalys failing around 55% or 56%
1. with .pat from build (got via WinSCP)
2. with .pat from Synology, started with the lowest 7.0.x version till the last 7.1.x
- deleted all disks and removed all partitions

still failing the upload at 55%.

02/06/2022 
- now trying with the new v.0.8.0.0

**Comment by dipol0** [comment]
@aniston and? Worked? PS may be try [this guide for dsm7.1](https://xpenology.com/forum/topic/60130-redpill-tinycore-loader-installation-guide-for-dsm-71-baremetal/) ?

**Comment by pocopico** [comment]
55% corrupt is 99% of the times either wrong usb VID:PID setting or wrong option selected at GRUB

**Comment by aniston** [comment]
@dipol0 did not work even with todays latest rploader v 0.8.0.1
- actually i have been following the guide from peter_suh you mentioned in the link.
- tried to compile for DSMv7.0.1_42218 as well as the latest 7.1.0_42661 both reboot at about 55%
- in the web console i can see with fdisk -l that the /dev/sda partitions are created correctly (8GB and 2GB)

@pocopico if the VID:PID settings were not correct i guess we would not have landed uptill the Synology installation web interface, or I'm missing a point there ?
- also if GRUB has a wrong option selected then the empty disk used to install the DSM would not get formatted to 8GB and 2GB partitions , just my logical observations ;)

hier ist a copy of the fdisk output from the web terminal ::
```
DiskStation> fdisk -l
Disk /dev/sda: 298 GB, 320072933376 bytes, 625142448 sectors
38913 cylinders, 255 heads, 63 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Device  Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type
/dev/sda1    0,130,3     1023,254,63       8192   16785407   16777216 8192M fd Linux raid autodetect
/dev/sda2    1023,254,63 1023,254,63   16785408   20979711    4194304 2048M fd Linux raid autodetect
Disk /dev/sdu: 1928 MB, 2021654528 bytes, 3948544 sectors
1010 cylinders, 63 heads, 62 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Device  Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type
/dev/sdu1 *  0,32,33     6,62,56           2048     100351      98304 48.0M 83 Linux
Partition 1 has different physical/logical start (non-Linux?):
     phys=(0,32,33) logical=(0,33,3)
Partition 1 has different physical/logical end:
     phys=(6,62,56) logical=(25,43,36)
/dev/sdu2    6,62,57     15,205,62       100352     253951     153600 75.0M 83 Linux
Partition 2 has different physical/logical start (non-Linux?):
     phys=(6,62,57) logical=(25,43,37)
Partition 2 has different physical/logical end:
     phys=(15,205,62) logical=(65,0,62)
/dev/sdu3    15,205,63   130,138,8       253952    2097151    1843200  900M 83 Linux
Partition 3 has different physical/logical start (non-Linux?):
     phys=(15,205,63) logical=(65,1,1)
Partition 3 has different physical/logical end:
     phys=(130,138,8) logical=(536,57,2)
Disk /dev/md0: 8191 MB, 8589869056 bytes, 16777088 sectors
2097136 cylinders, 2 heads, 4 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Disk /dev/md0 doesn't contain a valid partition table
Disk /dev/md1: 2047 MB, 2147418112 bytes, 4194176 sectors
524272 cylinders, 2 heads, 4 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Disk /dev/md1 doesn't contain a valid partition table
```

any help ideas are appreciated.

**Comment by aniston** [comment]
@pocopico , thanks for your explanation and reply.

restarting the whole procedure again (erasing everything from USB and HDD) i can see the `/dev/synoboot` devices in `fdisk -l` , but it still keeps restarting at 65%

The PID and VID are correctly listed in grub.cfg 
`linux /zImage withefi earlyprintk syno_hw_version=DS3615xs console=ttyS0,115200n8 netif_num=1 pid=0x1000 earlycon=uart8250,io,0x3f8,115200n8 syno_port_thaw=1 mac1=F01FAF47C787 sn=1230LWN019412 vid=0x8564 elevator=elevator loglevel=15 HddHotplug=0 DiskIdxMap=00 syno_hdd_detect=0 vender_format_version=2 syno_hdd_powerup_seq=0 log_buf_len=32M root=/dev/md0 SataPortMap=1 `
and also correctly identified with "identifyusb" as seen here in the user_config.json , this time round i'm simulating with a DS3615xs:
```
{
  "extra_cmdline": {
    "pid": "0x1000",
    "vid": "0x8564",
    "sn": "1230LWN019412",
    "mac1": "F01FAF47C787",
    "SataPortMap": "1",
    "DiskIdxMap": "00"
  },
  "synoinfo": {
    "internalportcfg": "0xffff",
    "maxdisks": "16",
    "support_bde_internal_10g": "no",
    "support_disk_compatibility": "no",
    "support_memory_compatibility": "no"
  },
  "ramdisk_copy": {}
}
```

To be sure that I'm going the right way a list of the HW  used :
- Baremetal Dell laptop Latitude E6530 Intel Core i5-3230M with 8GB RAM
- one USB 2GB stick with TCRP v0.8.0.0 and today's fresh TCRP v0.8.0.1
- one Single SATA 320GB HDD (erasing the partitions manually before retrying different builds)
- an intel Pro1000 (e1000e) compatible Network adapter

the Installation steps used reflect the forum [link ](https://xpenology.com/forum/topic/60130-redpill-tinycore-loader-installation-guide-for-dsm-71-baremetal) using [tinycore-redpill.v0.8.0.0.img.gz](https://github.com/pocopico/tinycore-redpill/blob/main/tinycore-redpill.v0.8.0.0.img.gz)
```
./rploader.sh update now
./rploader.sh fullupgrade now
./rploader.sh serialgen DS3615xs realmac
./rploader.sh identifyusb now
./rploader.sh satamap now
cat user_config.json
sync
./rploader.sh build  bromolow-7.0.1-42218
sync
./rploader.sh clean now
./rploader.sh build bromolow-7.1.0-42661
sync
(got ds3615xs_42661.pat via winscp)
./rploader.sh clean now; rm -rf /mnt/sdb3/auxfiles; rm -rf /home/tc/custom-module; ./rploader.sh backup now;
sync
sudo reboot
```
- and selected USB boot 

From the web based terminal after 50% of the installation fdisk -l results like this (Disk /dev/synoboot is there) :

```
DiskStation> fdisk -l
Disk /dev/sda: 298 GB, 320072933376 bytes, 625142448 sectors
38913 cylinders, 255 heads, 63 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Device  Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type
/dev/sda1    0,130,3     1023,254,63       8192   16785407   16777216 8192M fd Linux raid autodetect
/dev/sda2    1023,254,63 1023,254,63   16785408   20979711    4194304 2048M fd Linux raid autodetect
Disk /dev/synoboot: 1928 MB, 2021654528 bytes, 3948544 sectors
1010 cylinders, 63 heads, 62 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Device       Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type
/dev/synoboot1 *  0,32,33     6,62,56           2048     100351      98304 48.0M 83 Linux
Partition 1 has different physical/logical start (non-Linux?):
     phys=(0,32,33) logical=(0,33,3)
Partition 1 has different physical/logical end:
     phys=(6,62,56) logical=(25,43,36)
/dev/synoboot2    6,62,57     15,205,62       100352     253951     153600 75.0M 83 Linux
Partition 2 has different physical/logical start (non-Linux?):
     phys=(6,62,57) logical=(25,43,37)
Partition 2 has different physical/logical end:
     phys=(15,205,62) logical=(65,0,62)
/dev/synoboot3    15,205,63   130,138,8       253952    2097151    1843200  900M 83 Linux
Partition 3 has different physical/logical start (non-Linux?):
     phys=(15,205,63) logical=(65,1,1)
Partition 3 has different physical/logical end:
     phys=(130,138,8) logical=(536,57,2)
Disk /dev/md0: 8191 MB, 8589869056 bytes, 16777088 sectors
2097136 cylinders, 2 heads, 4 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Disk /dev/md0 doesn't contain a valid partition table
```

#### is there any way to trace the installation log or where can i figure out what is not getting done , that may help to resolve this problem ?

**Comment by pocopico** [comment]
Ok now that you see the synoboot disk it’s a different issue. Did you use the pat file that you’ve downloaded from syno right ? Not the one that is cached on the usb loader.

**Comment by aniston** [comment]
> Ok now that you see the synoboot disk it’s a different issue. Did you use the pat file that you’ve downloaded from syno right ? Not the one that is cached on the usb loader.

I tried with both the one generated from the build on the USB (and each time erasing the HDD) and from Synology.

**Comment by pocopico** [comment]
First two partitions hold the root and the swap.  The third will hold your data if and when you create a volume after install

**Comment by dipol0** [comment]
@pocopico hi. U can create Release page on Github with older releases images, 0.4 for example..? tnx

**Comment by aniston** [comment]
@pocopico , I managed to get to a working DS3622xs+ by plugging the USB Loader into another USB port on the Baremetal HW, So my issue was resolved by moving the USB bootloader stick to another PC USB port.

The idea came out of a post from you on the forum suggesting to try out a different USB port, thanks for that.

Q. Logically why is this happening ! TCRP and the USB bootloader USB stick actually manage to boot the PC to start with, so how come it looses it at a later stage ?

- anyways, when the OP @GuS-eu can try this out then based on the feedback accordingly you can close the issue.

**Comment by sojab0on** [comment]
I have some waht of the same issue i cant get the generated .pat from tinycore when i do win scp it states 
The system cannot find the file specified but the file is there i checked tinycore in the auxfile and home html directory still no go
