### ISSUE TITLE
Could not determine if file .pat is encrypted or not, maybe corrupted

### ISSUE THREAD

**Issue by damienmillet** [pocopico/tinycore-redpill#298]
**To Reproduce**
- select model
- select version
- click realmac
- build

**Screenshots**
![Capture d’écran 2023-05-16 à 21 47 21](https://github.com/pocopico/tinycore-redpill/assets/12233383/b368f244-6faf-4277-9c92-44c6e6bfeeba)

**Desktop (please complete the following information):**
- HTML
- Browser safari
- Version ds3622xsp-7.2.0-64551

**Additional context**
To fix it I must wget it from /config file

**Comment by pocopico** [comment]
OK, i found the reason for 99% stuck and i think i've fixed that.

Download latest image and burn again. Do not just update, Its a problem in the image itself.

**Comment by damienmillet** [comment]
ok ! just coming back right now, so I ll looking about a web possibility if u want it

**Comment by gregsef** [comment]
Hi
 I have the same problem on proxmox I have done one VM fine with a previous package et now any vm I am trying to make I have got this error message
Damien what do you mean by lookin about a web possibility..
:-)

**Comment by lzzsalvo** [comment]
> Download latest image and burn again. Do not just update, Its a problem in the image itself.
Hi, I just tried with the image I just downloaded but the problem persists. Attached the logs

[buildlog.txt](https://github.com/pocopico/tinycore-redpill/files/11814901/buildlog.txt)

**Comment by lzzsalvo** [comment]
no! ram is 6gbIl giorno 21 giu 2023, alle ore 17:07, pocopico ***@***.***> ha scritto:﻿
Do you maybe have memory less than 2GB ? That can be the case

**Comment by pocopico** [comment]
Ok, then perform a full upgrade running 

./reloaded.sh fullupgrade

**Comment by lzzsalvo** [comment]
Now is ok. Thx

Il giorno gio 22 giu 2023 alle ore 09:38 pocopico ***@***.***>
ha scritto:
